name: Node.js CI

on:
  push:
    branches:
      - main  # Adjust this branch name according to your setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build

      - name: Test
        run: npm test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
          -Dsonar.projectKey=Hymn_sonarQube \
          -Dsonar.projectName="Your Project Name" \
          -Dsonar.projectVersion=1.0 \
          -Dsonar.sources=src \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONAR_TOKEN
